### PR TITLE
LED proxy test

### PR DESCRIPTION
**Pull request by annamcniff**
This is basically what I added, it's commented out and in the toggle switch section, we can also use this strategy to test the IR emulators :)
GPIO.setup(x,GPIO.OUT) #test led proxy for motor motion 
GPIO.setup(y,GPIO.OUT) #test led proxy for motor motion
if GPIO.input(toggle switch one direction) == 1 
GPIO.output(x, GPIO.HIGH) 
GPIO.output(y,GPIO.LOW)
if GPIO.input(toggle switch other direction) == 1 
GPIO.output(y, GPIO.HIGH) 
GPIO.output(x,GPIO.LOW)

### CODE REVIEW

**Review by amandabacon — COMMENTED** [review]
The toggle switch section was written for the little toggle switch I had originally thought would be used for the home position (it can only be thrown in one direction, so it will not work). We can talk about this more, but I think the relays are what will control the motor (and thus if the dome is moving clockwise or counter clockwise). This logic you wrote would probably go under the relay section and would somehow incorporate the 4 relays (as 2 are hardware safety measures). Does that kind of make sense? Otherwise, like the idea.

**Comment by annamcniff** [comment]
Yeah lol rip I thought that was the back and forth motion like instead of
buttons I’ll move the logic to the relays :)

**Comment by annamcniff** [comment]
Just went through the existing relay code and I don't really see a place to put this yet and I tried to start figuring it out but I don't know how the states from the whiteboard (A and B) correspond to GPIO pin configuration/signaling, is there a diagram of that that I'm missing? Thanks!

DomeProjectBoard

**Comment by amandabacon** [comment]
Yeah...as I was responding I realized I was not quite sure how that would work. I think the first step is to figure out how the relays work. I have one that is basically setup, but needs the actual relay soldered on. We will keep this open and build upon it.

**Comment by annamcniff** [comment]
Ok cool!

**Pull request closed without merging**
